#!/usr/bin/env python3
"""
Appendix A tables for the 63-field NADICS extraction schema.

Reads nadics-feature-importance.json, the input of record that also drives
Figure 3.4, and writes two LaTeX fragments one level up, in figures/, where
content/appendix.tex inputs them:

  nadics-feature-importance-ranking.tex   all 63 fields in rank order (longtable)
  nadics-feature-importance-groups.tex    importance by field group (float)

Both fragments are generated: change the JSON or this script, never the
output. Captions are prose and stay in content/appendix.tex, which defines
\\nadicsRankingCaption and \\nadicsGroupsCaption before the \\input.

The in-cell bars use the TUM Corporate Design print ramp of the figure, one
shade per group, so a row can be matched to Figure 3.4 by colour. Standard
library only, so any python3 runs it.
"""

import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent
DATA = json.loads((HERE / "nadics-feature-importance.json").read_text())

GROUPS = ["A", "B", "C", "D", "E"]
COLOR = {                            # as in nadics-feature-importance.py
    "A": "003359",                   # TUM Blau dunkel 2
    "B": "005293",                   # TUM Blau dunkel 1
    "C": "0065BD",                   # TUM Blau
    "D": "64A0C8",                   # Akzent Pantone 542
    "E": "98C6EA",                   # Akzent Pantone 283
}
# Short group names for the ranking table, as the chapter prose uses them
# ("flow fields", "timing fields", ...); the group table gives the full names.
SHORT = {"A": "Flow", "B": "Timing", "C": "Protocol", "D": "Relational",
         "E": "Process"}
BAR_MM_PER_PERCENT = 2.0             # the top field, 11.93 per cent, is 23.9 mm
BAR = r"\textcolor{{nadics{g}}}{{\rule[0.1ex]{{{w:.2f}mm}}{{1.3ex}}}}"

feats = sorted(DATA["features"], key=lambda f: f["rank"])
gname = DATA["group_names"]
gcount = DATA["group_field_counts"]
gshare = DATA["group_importance_percent"]
N = len(feats)

# The tables restate the JSON, so check that it is internally consistent first.
assert [f["rank"] for f in feats] == list(range(1, N + 1)), "ranks are not 1..N"
assert N == sum(gcount.values()) == 63, N
assert abs(sum(f["importance_percent"] for f in feats) - 100) < 1e-9
for g in GROUPS:
    members = [f for f in feats if f["group"] == g]
    assert len(members) == gcount[g], g
    assert abs(sum(f["importance_percent"] for f in members) - gshare[g]) < 1e-9, g


def tt(name):
    return r"\texttt{" + name.replace("_", r"\_") + "}"


PREAMBLE = [
    "% Generated by figures/src/nadics-feature-importance-table.py from",
    "% figures/src/nadics-feature-importance.json. Do not edit by hand.",
    *(rf"\definecolor{{nadics{g}}}{{HTML}}{{{COLOR[g]}}}" for g in GROUPS),
]

# ------------------------------------------------------ ranking (Table A.1) --
head = [
    r"  \toprule",
    r"  Rank & ID & Field & Group & Importance & Cumulative & \\",
    r"       &    &       &       & (\%)   & (\%)       & \\",
    r"  \midrule",
]
rows, cum = [], 0.0
for f in feats:
    v = f["importance_percent"]
    cum += v
    bar = BAR.format(g=f["group"], w=v * BAR_MM_PER_PERCENT)
    rows.append(
        f"  {f['rank']:>2d} & {f['feature_id']:<3s} & {tt(f['feature']):<32s} & "
        f"{SHORT[f['group']]:<10s} & {v:5.2f} & {cum:6.2f} & {bar} \\\\")

ranking = PREAMBLE + [
    r"\begingroup",
    r"\small",
    r"\setlength{\tabcolsep}{5pt}",
    r"\setlength{\LTcapwidth}{\linewidth}",
    r"\begin{longtable}{@{}rlllrrl@{}}",
    r"  \caption{\nadicsRankingCaption}\label{tab:app:nadics-ranking}\\",
    *head,
    r"\endfirsthead",
    r"  \caption[]{(continued)}\\",
    *head,
    r"\endhead",
    r"  \bottomrule",
    r"  \multicolumn{7}{r@{}}{\footnotesize\itshape continued on the next page}\\",
    r"\endfoot",
    r"  \bottomrule",
    r"\endlastfoot",
    *rows,
    r"\end{longtable}",
    r"\endgroup",
]

# ----------------------------------------------------- groups (Table A.2) --
grows = []
for g in GROUPS:
    best = min(f["rank"] for f in feats if f["group"] == g)
    swatch = BAR.format(g=g, w=2.2)
    grows.append(
        f"    {g} & {swatch}\\ {gname[g]:<21s} & {gcount[g]:>2d} & "
        f"{gshare[g]:6.2f} & {gcount[g] / N * 100:6.2f} & "
        f"{gshare[g] / gcount[g]:4.2f} & {best:>2d} \\\\")

groups = PREAMBLE + [
    r"\begin{table}[tbp]",
    r"  \centering",
    r"  \caption{\nadicsGroupsCaption}",
    r"  \label{tab:app:nadics-groups}",
    r"  \small",
    r"  \begin{tabular}{@{}llrrrrr@{}}",
    r"    \toprule",
    r"    \multicolumn{2}{@{}l}{Group} & Fields & Importance & Field & Importance & Highest \\",
    r"    & & & share (\%) & share (\%) & per field (\%) & rank \\",
    r"    \midrule",
    *grows,
    r"    \midrule",
    f"    \\multicolumn{{2}}{{@{{}}l}}{{All groups}} & {N} & "
    f"{sum(gshare.values()):6.2f} & {100:6.2f} & {100 / N:4.2f} & \\\\",
    r"    \bottomrule",
    r"  \end{tabular}",
    r"\end{table}",
]

for name, lines in (("nadics-feature-importance-ranking.tex", ranking),
                    ("nadics-feature-importance-groups.tex", groups)):
    (OUT / name).write_text("\n".join(lines) + "\n")
    print(f"wrote figures/{name}")

print(f"cumulative at 10 / 24 / 36: "
      + " / ".join(f"{sum(f['importance_percent'] for f in feats[:k]):.2f}"
                   for k in (10, 24, 36)))
